### PR TITLE
chore(refactor): Refactored code based

### PR DESCRIPTION
**Pull request by gonzalovazquez**
Added imgurService, as well did some general refactoring of the code base.

Will be writing tests for the imgurService next.

### CODE REVIEW

**Comment by gonzalovazquez** [comment]
Let me know if you have any questions. We can code review here.

**Comment by joeyism** [comment]
I keep getting two errors, the second caused by the first. The first is 
TypeError: Cannot read property 'protocol' of undefined

**Comment by joeyism** [comment]
Nvm, fixed it

**Comment by gonzalovazquez** [comment]
What was the fix?

On Wed, Feb 4, 2015 at 8:49 PM, Joey Sham notifications@github.com wrote:

> Nvm, fixed it
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joeyism/imgur-lite/pull/1#issuecomment-72979937.

## 

Gonzalo Vazquez
email: gonzalo.segura1@gmail.com
web: gonzalovazquez.ca
twitter: @gonzalovazzquez https://twitter.com/gonzalovazzquez
cell: 416-910-2047

**Comment by joeyism** [comment]
I'm wondering if it's the version. $http('get',object) -> $http,get(object). I thought both works regardless

**Comment by gonzalovazquez** [comment]
Yep, both are valid ways of using $http.

The difference is just in the implementation. Most services would use the more verbose version, since you want the service to be more flexible. https://code.angularjs.org/1.3.10/docs/api/ng/service/$http#usage

Do you still get the TypeError: Cannot read property 'protocol' of undefined ?

**Comment by joeyism** [comment]
The error was gone after I changed $http('get',object) -> $http,get(object). I can't test it much anymore though. I exceeded the limits I'm allowed and I've requested more limits...

**Pull request merged**
